### PR TITLE
fix change name modulo for module .

### PR DESCRIPTION
**Pull request by Daniel-Dos**
Little correction in name.

### CODE REVIEW

**Comment by chkal** [comment]
Thanks a lot! Good catch. This doesn't look correct. 

But to be honest, I'm note sure if "module" is the correct replacement. In EDR1 the Latex source looked like this:

```
Likewise, injection of fields and properties is unrestricted and fully compatible 
with \jaxrs\ ---modulo the restrictions explained in Section \ref{controller_instances}.
```

Not sure what this sentence should mean. Something like "except" or "including" would make sense, but theses words look very different from "modulo".

Any other thoughts?

**Comment by chkal** [comment]
I agree with @ivargrimstad.

@Daniel-Dos: Could you perhaps adjust the wording as proposed?

**Comment by Daniel-Dos** [comment]
Hello, 
I will adjust as proposed by ivar.

thank you so much.

**Comment by chkal** [comment]
Looks good to me!

**Comment by chkal** [comment]
I just merged this one! Thanks @Daniel-Dos!

**Pull request merged**
