### PR TITLE
URL Building in the template example

### PR DESCRIPTION
**Pull request by phillip-kruger**
Small change in the Spec (2.3.1. Building URIs in a View) to add the missing comma (as discussed here: https://groups.google.com/forum/#!topic/jsr371-users/vSd9WnTsEag)

Also updated the JavaDoc in javax.mvc.MvcContext and added the missing comma.

### CODE REVIEW

**Comment by lefloh** [comment]
LGTM but would be great if the PR would just contain the latest commit.

**Comment by phillip-kruger** [comment]
Yes sorry I need to rebase.

**Comment by ivargrimstad** [comment]
A tip: Create a new branch from head of master and do your changes there. It is never a good practice to do a PR from your master... 

I think I will close this PR and let you open a new one

**Comment by phillip-kruger** [comment]
Thanks for the tip :) I have now done it that way.

**Pull request closed without merging**
