### PR TITLE
link to javadoc

### PR DESCRIPTION
**Pull request by Daniel-Dos**
fix in link of javadoc . #201

### CODE REVIEW

**Comment by chkal** [comment]
Looks good to be. But let's wait for the PFD release before merging it.

**Comment by Daniel-Dos** [comment]
ok. 
thanks.

**Comment by chkal** [comment]
Merged! Thanks!

BTW: This is the first pull request targeted for the "Final Draft" release 1.0-fd! :beers:

**Comment by Daniel-Dos** [comment]
looking forward to the final version.  :smiley:  :beers:

**Pull request merged**
