### PR TITLE
Latex to Asciidoc

### PR DESCRIPTION
**Pull request by phillip-kruger**
Added new asciidoc to create the spec PDF. The latex is still available, one you are happy with the new asciidoc we can delete that.

### CODE REVIEW

**Comment by ivargrimstad** [comment]
I suggest we merge this PR to a intermediate branch for potential adjustments. E.g. the section referencing etc. When we are 100% happy, we merge it to master and get rid of the Latex version.

**Comment by chkal** [comment]
Unfortunately I didn't fine time to have a deeper look at the PR yet. Sorry about that.

But I agree with @ivargrimstad that we should soon merge this into a separate branch so that we can continue some fine tuning there.

One minor thing: Could you perhaps remove these `.directory` files? Looks like you added them to the `.gitignore` file but they have been committed to the repository before!?!

Thank you so much for you help with this. This is awesome!

**Comment by phillip-kruger** [comment]
Ok removed the .directory files.

**Comment by ivargrimstad** [comment]
Let's continue work on mvc-spec:feature/106

**Comment by chkal** [comment]
I just had another quick look at the branch. IMO it is in a really good shape. I'm not sure if there is anything we need to do before merging it. Actually we want to get rid of the Latex version and I don't think that the section referencing is a blocker for us. So what do you think of merging it to master?

**Pull request merged**
