### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by lefloh**
* Added change from MVC_SPEC-64 to changelog
* Added a Facelets hello world example
* Clarified that CDI support is only optional for view engines not implementations

### CODE REVIEW

**Comment by chkal** [comment]
Awesome! Thanks a lot! Look great! One question though:

I'm a bit surprised that the `<h:*` tags work as expected. My impression was, that only the `<ui:*` Facelets tags work as expected. But I never tried this to be honest. It feels weird to use JSF components for rendering the MVC view.

**Comment by lefloh** [comment]
Thanks for the hint! I started a discussion in the [mvc-spec users-list](https://java.net/projects/mvc-spec/lists/users/archive/2016-07/message/5).

**Comment by lefloh** [comment]
I moved the Facelets commit to [PR #11](https://github.com/mvc-spec/mvc-spec/pull/10).

**Comment by chkal** [comment]
I just merged this one. I had to merge manually because of merge conflicts in the PDF file. But everything looks fine so far. Thanks a lot!

**Pull request closed without merging**
