### PR TITLE
Updated API for new license 

### PR DESCRIPTION
**Pull request by chkal**
Hey all,

this pull requests updates the API module for the new ASL license. I did the following things:

  1. I added the license-maven-plugin and a new template for the license header (see https://github.com/chkal/mvc-spec/commit/86887f194eba39ad150f4e2c0ea456201391e5fd)
  2. I executed `mvn license:format` which basically updated the license header for all files (see https://github.com/chkal/mvc-spec/commit/cfbd3da0f2d36018e5833e6c5be5c9bef38b6883)
  3. I replaced the `LICENSE.html` file with the ASL `LICENSE.txt` file (see https://github.com/chkal/mvc-spec/commit/ab297f5e9c492dd735642946842359e1a825cc86)

What do you think?

Christian

### CODE REVIEW

**Comment by Daniel-Dos** [comment]
Hi @chkal, 

This is great updates.

I have two questions:

1 - Should not your name also go along with the license?
2 - How does this maven plugin for licensing work? When running the informator command for you does it automatically update the headers?

Thank you.

**Comment by chkal** [comment]
Hey @Daniel-Dos,

thanks for reviewing. Regarding your questions:

From a legal perspective @ivargrimstad is the copyright owner. So we decided to use his name in the header.

The Maven plugin works like this: When the build is executed, the plugin checks if all license headers are correct. You can also run this check manually:

    mvn license:check

If there are failures in this check (for example if a class was added which doesn't contain the correct header), then you can run this command to fix the problem:

    mvn license:format

That's it.

**Comment by ivargrimstad** [comment]
It looks great!
Ok to merge by me,

**Comment by Turini** [comment]
It's ok to merge by me too. thks christian

**Comment by Daniel-Dos** [comment]
Hey @chkal 

Thank you very much for the explanations.

I tested the maven plugin here and it's fantastic, it makes it much easier when you upgrade.

**Comment by chkal** [comment]
Hey all,

unfortunately I had to make some minor adjustments to the pull request. The three added commits contain the following changes:

  1. The license plugin is now configured to check specific file patterns. That's good because otherwise it would check EVERYTHING, include files like `.editorconfig`.
  2. I remove the custom file header template and now use the default ASL template which is included with the plugin. I did this because custom templates won't work well in multi module builds and we want to use the same config with Ozark to be consistent.
  3. I executed `mvn license:format` again so that all file headers got updated. The only change is that Ivar's email address is added to the header.

I hope everyone is fine with these changes.

PS: We should squash this PR into a single commit when merging so we get a nice clean history.

**Pull request merged**
